services:
  - type: web
    name: server
    runtime: docker
    plan: starter
    region: singapore
    branch: staging
    dockerfilePath: ./apps/server/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: WEBSITE_URL
        value: https://staging.shopora-website.pages.dev
      - key: CORS_ORIGINS
        value: https://staging.shopora-website.pages.dev,https://staging.shopora-dashboard.pages.dev
